### ISSUE TITLE
Bump versions

### ISSUE THREAD

**Issue by RMeissnerCC** [openeduhub/metalookup#99]
A lot of outdated packages, at least according to pyproject.toml
![image](https://user-images.githubusercontent.com/50482279/169825461-42b12f2a-5d9d-4c4e-b691-2793bf516b9c.png)

**Comment by MRuecklCC** [comment]
Really weird ... I ran `poetry update` a couple of times now, but it somehow does not pick up the new versions. I had to `poetry remove fastapi` and `poetry add fastapi` to get it to pick up the new version.

Nevermind - https://stackoverflow.com/a/54720073/2160256 has the answer (when reading carefully): `foobar = "^0.13"` not update to `foobar = "^0.14"` because that would change the leftmost non-zero version.

**Comment by RMeissnerCC** [comment]
So that means you switch to "~" instead of "^"? Thanks for the research1

**Comment by MRuecklCC** [comment]
> So that means you switch to "~" instead of "^"? Thanks for the research!

No unfortunately that does not work either. For dependencies that do not yet have a major version 1 released, one has to either manually `poetry remove` and `poetry add` them, or alternatively manually bump the versions in `pyproject.toml` and then run `poetry update && poetry install`.

**Comment by RMeissnerCC** [comment]
> > So that means you switch to "~" instead of "^"? Thanks for the research!
> 
> No unfortunately that does not work either. For dependencies that do not yet have a major version 1 released, one has to either manually `poetry remove` and `poetry add` them, or alternatively manually bump the versions in `pyproject.toml` and then run `poetry update && poetry install`.
> 
> This kind-of makes sense, as for those dependencies the `minor` version part may still break compatibility and is hence treated like the `major` version part :-)

-_- sad. I had hopes poetry would be able to deal with such cases :/
